[package]
name = "miniquad-websockets"
version = "0.1.0"
authors = ["Michael Birtwell <michael.birtwell@starleaf.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
